steps:
# Install dependencies
- name: node:$_NODE_VER
  entrypoint: npm
  args: ['install']
# Run tests
- name: node:$_NODE_VER
  entrypoint: npm
  args: ['test']
# Run custom commands
- name: node:$_NODE_VER
  entrypoint: npm
  args: ['run', 'build']
- name: gcr.io/galloro-gke/pack
  args: ['build','--builder','cnbs/sample-builder:bionic','europe-docker.pkg.dev/galloro-gke/gcb-study/nodesample:${_NODE_VER}']
images:
- 'europe-docker.pkg.dev/galloro-gke/gcb-study/nodesample:${_NODE_VER}'

