steps:
# Install dependencies
- name: node:$_NODE_VER
  entrypoint: npm
  args: ['install']
# Run tests
- name: node:$_NODE_VER
  entrypoint: npm
  args: ['test']
# Run custom commands
- name: node:$_NODE_VER
  entrypoint: npm
  args: ['run', 'build']
